# Generated by Django 2.1.3 on 2018-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
