# Generated by Django 2.1.3 on 2018-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20181111_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grad_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='duty',
            name='position',
        ),
        migrations.DeleteModel(
            name='Duty',
        ),
    ]
