# Generated by Django 2.1.3 on 2018-11-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_auto_20181111_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='thumbnail',
            field=models.ImageField(upload_to='places/'),
        ),
    ]
